### ISSUE TITLE
This thing drove me crazy

### ISSUE THREAD

**Issue by Rikko1204** [RingoftheKing/TowerDefenseBasics#43]
Tile can be selected and clicked even though turret shop not selected, which causes error.
Tile with turret will flash hover color when turret shop selected (it's not suppose to).

**Comment by RingoftheKing** [comment]
Bug explanation:

If you attempt to click a tile which has been built on, there is no visual response. In order to build again, you have to press the shop icon twice to build again.

**Comment by Rikko1204** [comment]
Update: Main source of issue is turretSelected in BuildManager. It is set to null but immediately changes after Start method. Still finding out why.
